# Generated by Django 5.2 on 2025-07-03 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhealth', '0002_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='dhealth.profile')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p', to='dhealth.profile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhealth.slot')),
            ],
        ),
    ]
