# Generated by Django 5.2 on 2025-07-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhealth', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhealth.booking')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhealth.profile')),
            ],
        ),
    ]
