# Generated by Django 5.2.4 on 2025-07-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhealth', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
