# Generated by Django 5.2.4 on 2025-07-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhealth', '0005_chatmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
    ]
