# Generated by Django 4.2.23 on 2025-08-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhealth', '0006_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_label',
            field=models.CharField(choices=[('general', 'General'), ('prescription', 'Prescription')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
