# Generated by Django 4.2.23 on 2025-08-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhealth', '0007_chatmessage_download_count_chatmessage_file_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_title',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='file_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
