# Generated by Django 4.2.23 on 2025-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhealth', '0008_remove_chatmessage_download_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
