# Generated by Django 4.2.23 on 2025-08-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhealth', '0009_alter_chatmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='feedback_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
