# Generated by Django 4.2.23 on 2025-08-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhealth', '0010_booking_feedback_comment_booking_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='feedback_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
